### ISSUE TITLE
Deployment on actual robot

### ISSUE THREAD

**Issue by lif314** [dblanm/gnn-manip#1]
I'm absolutely excited to come across your work, and it's quite a coincidence that I also own a Panda(FR3) robotic arm. I would be immensely grateful if you could share the code you've implemented on your real robot. Thank you so much in advance!

**Comment by dblanm** [comment]
Hi @lif314, I'm planning to release the code for another paper that uses the same real control. I'll write here once that's published.

**Comment by lif314** [comment]
> Hi @lif314, I'm planning to release the code for another paper that uses the same real control. I'll write here once that's published.

Thank you very much for your reply! Looking forward to your new work!
